image:
  - Ubuntu2004
  - Ubuntu1604
  - Ubuntu1804

stack: mysql, redis

environment:
  DB_PASS: Password12!
  DB_HOST: localhost
  DB_USER: root
  DB_NAME: bhima_test
  CORAL_REUSE_BROWSER: 1
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "12"

matrix:
  fast_finish: true

skip_branch_with_pr: true
clone_depth: 5

install:
  - mysql --version
  - sh: nvm install $nodejs_version
  - bash ./sh/setup-ci-env.sh
  - bash ./sh/appveyor.sh
  - yarn

build: off

services:
  - mysql
  - redis

test_script:
  - yarn build
  - yarn build:db
  - yarn test:server-unit
  - yarn test:client-unit
  - yarn test:integration
