image:
  - Ubuntu1604
  - Ubuntu1804

stack: mysql, redis

environment:
  DB_PASS: Password12!
  DB_HOST: localhost
  DB_USER: root
  DB_NAME: bhima_test
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "12"

install:
  - sh: nvm install $nodejs_version
  - bash ./sh/setup-ci-env.sh
  - bash ./sh/appveyor.sh
  - yarn

build: off

services:
  - mysql
  - redis

test_script:
  - yarn build
  - yarn build:db
  - yarn test:server-unit
  - yarn test:client-unit
  - yarn test:integration
